[workspace]
members = [
    "call-home",
    "console-logger",
    "metrics-exporter",
    "k8s/plugin",
    "k8s/supportability",
    "k8s/upgrade",
]

exclude = ["./dependencies/control-plane"]
resolver = "1"
